data example;
   array SRA $8 SRA13-SRA21;
   do id = 1 to 5;
      do i = 1 to dim(sra);
         sra[i] = put(ranuni(1),best8.);
         end;
      output;
      end;
   attrib sra: label='This is the label';
   drop i;
   run;
proc print;
   run;
proc transpose data=example out=tall;
   by id;
   var sra:;
   run;
data tallV / view=tallv;
   set tall;
   num = input(col1,f8.);
   run;
proc transpose data=tallv out=want(drop=_name_);
   by id;
   run;
proc contents varnum;
   ods select position;
   run;
proc print;
   run;
      