

DATA NEWACCOUNTS;
INFILE "C:\Users\Pratik\Desktop\Data Science Learning\Example Datasets\Applied Regression Analysis\newaccounts.csv" DSD FIRSTOBS=2;
INPUT SIZE NEW NEW2 ;
RUN;

ODS GRAPHICS ON;
PROC REG DATA=WORK.NEWACCOUNTS;
TITLE "LACK-OF-FIT TEST FOR SIMPLE LINEAR REGRESSION MODEL" ;
MODEL NEW = SIZE / LACKFIT ;
RUN;


