
/* Obtaining extreme values from a dataset by a variable */

PROC SORT DATA=DATA OUT=WORK.SORTED_DATA;
BY VAR;
RUN;

DATA HIGH LOW;
	SET SORTED_DATA(OBS=5) /* FOR 5 LOW AND HIGH VALUES */
	END=LAST_ROW;
	OUTPUT HIGH;
	IF LAST_ROW THEN
		DO READ_OBS = TOTAL_OBS TO 
						TOTAL_OBS - 1 BY -1 ;
			SET SORTED_DATA POINT=READ_OBS NOBS=TOTAL_OBS ;
			OUTPUT LOW;
	END;
RUN;

