
/* How to create a Simple Random Sample with Replacement */

DATA SUBSET;
	DO INDICATOR = 1 TO 10;
		PICK = CEIL(RANUNI(0)*TOTAL_OBS);
		OBS_PICKED = PICK;
		SET WORK.DATA POINT=PICK NOBS=TOTAL_OBS;
		OUTPUT;
	END;
STOP;
RUN;

/* Example */

DATA WORK.BURROW_SUBSET;
	DO I = 1 TO 50;
		SELECTED = CEIL(RANUNI(0)*TOTAL);
		OBS = SELECTED;
		SET SASHELP.BURROWS POINT=SELECTED NOBS=TOTAL ;
		OUTPUT;
	END;
	STOP;
RUN;