
/* Selecting a Simple Random Sample Without Replacement */

DATA SUBSET;
SAMPSIZE=10;
OBS_LEFT = TOTAL_OBS;
DO WHILE (SAMPSIZE > 0 AND OBS_LEFT > 0);
	PICK + 1;
IF RANUNI(0) < SAMPSIZE/OBS_LEFT THEN DO;
	SET WORK.DATA POINT=PICK NOBS=TOTAL_OBS ;
	OUTPUT;
		SAMPSIZE = SAMPSIZE - 1;
END;
OBS_LEFT = OBS_LEFT - 1 ;
END;
STOP;
RUN;


/* Example */

DATA WORK.BIRTHWGT_SUB;
SAMPLE_SZ = 10000 ;
SAM_SUBSET = TOTAL_CASES ;
DO WHILE (SAMPLE_SZ > 0 AND SAM_SUBSET > 0);
	PICKED + 1 ;
IF RANUNI(0) < SAMPLE_SZ/SAM_SUBSET THEN DO;
	SET SASHELP.BIRTHWGT POINT=PICKED NOBS=TOTAL_CASES ;
	OUTPUT;
	SAMPLE_SZ = SAMPLE_SZ - 1;
END;
SAM_SUBSET = SAM_SUBSET - 1 ;
END;
STOP;
RUN;


