
LIBNAME CLASS "C:\Users\Pratik\Desktop\Data Science Learning\Applied Regression Analysis";

ODS GRAPHICS ON;

/* CHECK INITIAL CORRELATIONS */
PROC CORR DATA=CLASS.CLASS_SURV;
VAR Drinking_Days Weekly_Study;
RUN;

/* FIT SIMPLE REGRESSION MODELS */
PROC REG DATA=CLASS.CLASS_SURV;
MODEL SATM = Drinking_Days  / ALPHA=0.05 ;
RUN;


PROC REG DATA=CLASS.CLASS_SURV;
MODEL SATM = Weekly_Study / ALPHA=0.05 ;
RUN;


/* FIT MULTIVARIATE MODEL */
PROC REG DATA=CLASS.CLASS_SURV;
MODEL SATM = Drinking_Days Weekly_Study / ALPHA=0.05 LACKFIT ;
RUN;



/* SUPPOSE WE HAVE MANY COVARIATES */
PROC REG DATA=CLASS.CLASS_SURV;
MODEL SATM = GPA Miss_Class Monthly_Parties Drinking_Days Weekly_Study HEIGHT WEIGHT BOOK_COST 
/ ALPHA=0.05 LACKFIT ;
RUN;


/* THIS IS THE REDUCED MODEL WHICH GIVES MORE PARSIMONY (SIMPLICITY) */
PROC REG DATA=CLASS.CLASS_SURV;
MODEL SATM =  Miss_Class   
/ ALPHA=0.05 LACKFIT GMSEP ;
RUN;